name: taksist
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest/Onest-Thin.ttf
          weight: 100
        - asset: assets/fonts/Onest/Onest-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Onest/Onest-Light.ttf
          weight: 300
        - asset: assets/fonts/Onest/Onest-Regular.ttf
          weight: 400
        - asset: assets/fonts/Onest/Onest-Medium.ttf
          weight: 500
        - asset: assets/fonts/Onest/Onest-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Onest/Onest-Bold.ttf
          weight: 700
        - asset: assets/fonts/Onest/Onest-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Onest/Onest-Black.ttf
          weight: 900
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
